_BASE_: "Base.yaml"
SOLVER:
  AMP:
    ENABLED: True
  TYPE: "sgd"
  IMS_PER_BATCH: 4
  BASE_LR: 0.0012
  STEPS: (69600, 92800)
  MAX_ITER: 116000
  WARMUP_ITERS: 3625
TEST:
  EVAL_PERIOD: 29000
VIS_PERIOD: 2320
DATASETS:
  TRAIN: ('SUNRGBD_train', 'SUNRGBD_val', 'Hypersim_train', 'Hypersim_val', 'ARKitScenes_train', 'ARKitScenes_val',  'nuScenes_train', 'nuScenes_val', 'KITTI_train', 'KITTI_val')
  TEST: ('SUNRGBD_test', 'Hypersim_test', 'ARKitScenes_test', 'KITTI_test', 'nuScenes_test') 
  CATEGORY_NAMES: ('chair', 'table', 'cabinet', 'car', 'lamp', 'books', 'sofa', 'pedestrian', 'picture', 'window', 'pillow', 'truck', 'door', 'blinds', 'sink', 'shelves', 'television', 'shoes', 'cup', 'bottle', 'bookcase', 'laptop', 'desk', 'cereal box', 'floor mat', 'traffic cone', 'mirror', 'barrier', 'counter', 'camera', 'bicycle', 'toilet', 'bus', 'bed', 'refrigerator', 'trailer', 'box', 'oven', 'clothes', 'van', 'towel', 'motorcycle', 'night stand', 'stove', 'machine', 'stationery', 'bathtub', 'cyclist', 'curtain', 'bin')
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 50