model:
  input_channels: 3
  output_channels: 64
  num_blocks: 5
  base_channels: 32
  channel_multiplier: 2
  condition_image_key: "depth_map"
  aggregation_method: 'attention'


training:
  batch_size: 32
  learning_rate: 0.0001
  num_epochs: 100
  weight_decay: 0.0001
  lr_scheduler:
    type: 'StepLR'
    step_size: 30
    gamma: 0.1

data:
  data_dir: 'data/processed/geometric'
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  augmentation:
    flip_probability: 0.5
    rotation_range: [-10, 10]
    brightness_range: [0.8, 1.2]
    contrast_range: [0.8, 1.2]

logging:
  log_interval: 100
  save_interval: 5000

device: 'cuda'
num_workers: 4
seed: 42

stable_diffusion_path: "stabilityai/stable-diffusion-2-1-base"
save_path: "checkpoints/geometric_controlnet.pth"