model:
  backbone: 'resnet34'
  num_classes: 1  # Only head class
  anchor_sizes: [32, 64, 128]
  aspect_ratios: [0.5, 1, 2]
  feature_map_sizes: [64, 32, 16]

training:
  batch_size: 8
  learning_rate: 0.0001
  num_epochs: 200
  weight_decay: 0.0001
  lr_scheduler:
    type: 'CosineAnnealingLR'
    T_max: 200
    eta_min: 0.000001

data:
  data_dir: 'data/processed/head_detection'
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  augmentation:
    flip_probability: 0.5
    rotation_range: [-20, 20]
    scale_range: [0.8, 1.2]
    translation_range: [-0.1, 0.1]

loss:
  classification_loss: 'FocalLoss'
  regression_loss: 'SmoothL1Loss'
  classification_weight: 1.0
  regression_weight: 1.0

nms:
  iou_threshold: 0.5
  score_threshold: 0.05

logging:
  log_interval: 20
  save_interval: 1000

evaluation:
  iou_thresholds: [0.5, 0.75]
  max_detections: 100

device: 'cuda'
num_workers: 4
seed: 42